8thSept2026/volAssignment/force-app/main/default/objects/Student__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Student_Categories</valueSetName>
    </valueSet>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Student__c/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Volunteer</label>
    <type>Checkbox</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/classes/StudentSelector.cls
public without sharing class StudentSelector {

    public static List<Student__c> getEligibleStudents( Set<String> categories) {

        return [
            SELECT Id,
                   Name,
                   Category__c
            FROM Student__c
            WHERE Active__c = true
            AND Volunteer__c = true
            AND Category__c IN :categories
        ];
        //Assuming total number of Students are lesser then 50k
    }
}