8thSept2026/volAssignment/force-app/main/default/objects/Assigned_Volunteer__c/Assigned_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Assigned Volunteer</label>
    <nameField>
        <label>Assigned Volunteer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

8thSept2026/volAssignment/force-app/main/default/objects/Assigned_Volunteer__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Assigned_Volunteer__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <label>Work Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Event_Work_Type</valueSetName>
    </valueSet>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Student__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Student_Categories</valueSetName>
    </valueSet>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/classes/AssignedVolunteerSelector.cls
public without sharing class AssignedVolunteerSelector {

    public static List<AggregateResult> getWorkloadByStudentIds(
        Set<Id> studentIds
    ) {
        return [
            SELECT Student__c studentId,
                   Event__r.Work_Type__c workType,
                   COUNT(Id) total
            FROM Assigned_Volunteer__c
            WHERE Student__c IN :studentIds
            GROUP BY Student__c, Event__r.Work_Type__c
        ];
    }

    public static List<Assigned_Volunteer__c> deleteAssignedVolunteer(
        List<Id> eventIds, List<Id> studentIds
    ) {
        return [
            SELECT Id FROM Assigned_Volunteer__c 
                        WHERE Student__c IN :studentIds
                        AND Event__c IN :eventIds
        ];
    }
    
    public static List<Assigned_Volunteer__c> getAssignedVolunteersByEventIds(
        List<Id> eventIds
    ) {
        return [
            SELECT Id,
                   Event__c,
                   Student__c,
                   Student__r.Name,
                   Student__r.Category__c
            FROM Assigned_Volunteer__c
            WHERE Event__c IN :eventIds
        ];
    }
}