8thSept2026/volAssignment/force-app/main/default/objects/Assigned_Volunteer__c/Assigned_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Assigned Volunteer</label>
    <nameField>
        <label>Assigned Volunteer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

8thSept2026/volAssignment/force-app/main/default/objects/Assigned_Volunteer__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Assigned_Volunteer__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/fields/Primary_Category__c.field-meta.xml
<CustomField>
    <fullName>Primary_Category__c</fullName>
    <label>Primary Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Student_Categories</valueSetName>
    </valueSet>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/fields/Required_Student_Count__c.field-meta.xml
<CustomField>
    <fullName>Required_Student_Count__c</fullName>
    <label>Required Student Count</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Occurred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <label>Work Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Event_Work_Type</valueSetName>
    </valueSet>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Student__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Student_Categories</valueSetName>
    </valueSet>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Student__c/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Volunteer</label>
    <type>Checkbox</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Workload_Defination__c/Workload_Defination__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Workload Defination</label>
</CustomObject>

8thSept2026/volAssignment/force-app/main/default/objects/Workload_Defination__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/classes/VolunteerAssignmentController.cls
public with sharing class VolunteerAssignmentController {
    /*
    	Fetch Event
		work type def map
		eligible students
		**getAssignmentCounts
		mapOFStudent w.r.t. already assigned workLoad.
 			x______________________________
		
	*/

    public static String assignVolunteers(Id volunteerWorkId) {

         
        // Fetch Event
        // will create Evewnt selector for this 
        Event__c work = [ SELECT Id, Work_Type__c, Primary_Category__c, Required_Student_Count__c, Status__c FROM Event__c
            				WHERE Id = :volunteerWorkId
            				LIMIT 1];

        Integer volunteersNeeded = Integer.valueOf(work.Required_Student_Count__c);
        if (volunteersNeeded <= 0)
            return 'Failed';
        
        // will create Work type def selector
        Map<String, Decimal> workloadWeights =  new Map<String, Decimal>();
        for (Workload_Defination__c workDef : Workload_Defination__c.getAll().values()) {
            workloadWeights.put(
                workDef.Name,
                workDef.Weight__c
            );
        }
        
         
        // Fetch eligible students
        List<Student__c> students = getEligibleStudents(work.Primary_Category__c);

        if (students.isEmpty()) 
            return 'Failed';

         
        // Fetch existing workload
        Map<Id, Integer> assignmentCountByStudent = getAssignmentCounts(students);
        
        Map<Id, Decimal> weightedWorkloadByStudent = getWeightedWorkload(students, workloadWeights);
        // till here am having StudentId, amt of workLoad 
                 return '';
    }


    private static List<Student__c> getEligibleStudents( String primaryCategory) {
        Set<String> eligibleCategories = new Set<String>{'Senior'};
        if(primaryCategory == 'Sub-Junior') 
            eligibleCategories.add('Sub-Junior');
        if(primaryCategory == 'Junior') {
            eligibleCategories.add('Sub-Junior');
            eligibleCategories.add('Junior');            
        }

        return [SELECT Id, Name, Category__c, Active__c, Volunteer__c FROM Student__c
                    WHERE Active__c = true
                            AND Volunteer__c = true
                            AND Category__c IN :eligibleCategories
        ];
    }

    private static Map<Id, Integer> getAssignmentCounts(List<Student__c> students) {
        Map<Id, Student__c> mapOfStudents = new Map<Id, Student__c>(students);
        Set<Id> studentIds = mapOfStudents.keySet();

        Map<Id, Integer> result = new Map<Id, Integer>();
        for (AggregateResult ar : [
            SELECT Student__c studentId,
                   COUNT(Id) assignmentCount
            FROM Assigned_Volunteer__c
            WHERE Student__c IN :studentIds
            GROUP BY Student__c
        ]) {
			System.debug('ar ' + ar);
            result.put(
                (Id)ar.get('studentId'),
                Integer.valueOf(
                    String.valueOf(ar.get('assignmentCount'))
                )
            );
        }

        return result;
    }

    private static Map<Id, Decimal> getWeightedWorkload(List<Student__c> students,Map<String, Decimal> weights) {
        Set<Id> studentIds = new Map<Id, Student__c>(students).keySet();

        Map<Id, Decimal> result = new Map<Id, Decimal>();

        for (Assigned_Volunteer__c assignment : [ SELECT Student__c, Event__r.Work_Type__c FROM Assigned_Volunteer__c WHERE Student__c IN :studentIds]) {
            Decimal weight = weights.get(assignment.Event__r.Work_Type__c);
            Decimal current = result.containsKey(assignment.Student__c)? 
                				result.get(assignment.Student__c): 
            					0;
            result.put(
                assignment.Student__c,
                current + weight
            );
        }

        return result;
    }
}