8thSept2026/volAssignment/force-app/main/default/objects/Assigned_Volunteer__c/Assigned_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Assigned Volunteer</label>
    <nameField>
        <label>Assigned Volunteer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assigned Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

8thSept2026/volAssignment/force-app/main/default/objects/Assigned_Volunteer__c/fields/Assigned_Date__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Date__c</fullName>
    <label>Assigned Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Assigned_Volunteer__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Assigned_Volunteer__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <label>Student</label>
    <referenceTo>Student__c</referenceTo>
    <relationshipLabel>Assigned Volunteers</relationshipLabel>
    <relationshipName>Assigned_Volunteers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/fields/Primary_Category__c.field-meta.xml
<CustomField>
    <fullName>Primary_Category__c</fullName>
    <label>Primary Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Student_Categories</valueSetName>
    </valueSet>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/fields/Required_Student_Count__c.field-meta.xml
<CustomField>
    <fullName>Required_Student_Count__c</fullName>
    <label>Required Student Count</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <label>Work Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Event_Work_Type</valueSetName>
    </valueSet>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Student__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Student_Categories</valueSetName>
    </valueSet>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Student__c/fields/Volunteer__c.field-meta.xml
<CustomField>
    <fullName>Volunteer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Volunteer</label>
    <type>Checkbox</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Workload_Defination__c/Workload_Defination__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Workload Defination</label>
</CustomObject>

8thSept2026/volAssignment/force-app/main/default/objects/Workload_Defination__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/classes/VolunteerAllocationHandlerTest.cls
@IsTest
private class VolunteerAllocationHandlerTest {

    @TestSetup
    static void setupData() {

        insert new List<Workload_Defination__c>{
            new Workload_Defination__c(Name = 'Class', Weight__c = 1),
            new Workload_Defination__c(Name = 'Branch', Weight__c = 2),
            new Workload_Defination__c(Name = 'Collage', Weight__c = 3)
        };

        insert new List<Student__c>{
            new Student__c(Name = 'Senior Student', Category__c = 'Senior', Active__c = true, Volunteer__c = true),
            new Student__c(Name = 'Junior Student', Category__c = 'Junior', Active__c = true, Volunteer__c = true),
            new Student__c(Name = 'Sub Junior Student', Category__c = 'Sub-Junior', Active__c = true, Volunteer__c = true)
        };
    }

    @IsTest
    static void testAssignVolunteersWithNullEventIdsRetunEmptyResult() {

        Test.startTest();
        List<VolunteerAllocationHandler.AssignVolunteersResponse> result = VolunteerAllocationHandler.assignVolunteers(null);
        Test.stopTest();

        System.assertEquals(0, result.size());
    }

    @IsTest
    static void testAssignVolunteerWithEmptyEventIdsReturnEmptyResult() {

        Test.startTest();
        List<VolunteerAllocationHandler.AssignVolunteersResponse> result = VolunteerAllocationHandler.assignVolunteers(new Set<Id>());
        Test.stopTest();

        System.assertEquals(0, result.size());
    }

    @IsTest
    static void testAssignVolunteerWithInvalidIdsReturnMessageInvalidEventIds() {

        Set<Id> ids = new Set<Id>{UserInfo.getUserId()};

        Test.startTest();
        List<VolunteerAllocationHandler.AssignVolunteersResponse> result = VolunteerAllocationHandler.assignVolunteers(ids);
        Test.stopTest();

        System.assertEquals(System.Label.Invalid_EventId_EventIds, result[0].statusMessage);
    }

    @IsTest
    static void testAssignVolunteerWithZeroRequiredStudentCountReturnFailedVolunteerAllocationNoRequiredCount() {

        Event__c eventRecord = new Event__c(
            Name = 'Zero Count Event',
            Primary_Category__c = 'Senior',
            Required_Student_Count__c = 0,
            Work_Type__c = 'Class'
        );

        insert eventRecord;

        Test.startTest();
        List<VolunteerAllocationHandler.AssignVolunteersResponse> result = VolunteerAllocationHandler.assignVolunteers(
                new Set<Id>{ eventRecord.Id }
            );
        Test.stopTest();
        Integer assignVolunteerCount =  [SELECT COUNT()
                                            FROM Assigned_Volunteer__c
                                            WHERE Event__c = :eventRecord.Id
                                        ];

        System.assertEquals(1, result.size());
        System.assertEquals(false, result[0].isSuccess);
        System.assertEquals(eventRecord.Id, result[0].eventId);
        System.assertEquals(eventRecord.Name + ' ' +System.Label.Failed_Volunteer_Allocation_No_Required_Count, result[0].statusMessage);
        System.assertEquals(0, assignVolunteerCount);
    }

    @IsTest
    static void testAssignVolunteersJuniorCategoryAllocationReturnSuccessMessageAndAllocatedVolunteerIds() {

        Event__c eventRecord = new Event__c(
            Name = 'Junior Event',
            Primary_Category__c = 'Junior',
            Required_Student_Count__c = 2,
            Work_Type__c = 'Class'
        );

        insert eventRecord;

        Test.startTest();
        List<VolunteerAllocationHandler.AssignVolunteersResponse> result = VolunteerAllocationHandler.assignVolunteers(
                new Set<Id>{ eventRecord.Id }
            );
        Test.stopTest();

        Integer assignVolunteerCount =  [SELECT COUNT()
                                            FROM Assigned_Volunteer__c
                                            WHERE Event__c = :eventRecord.Id
                                        ];

        System.assertEquals(1, result.size());
        System.assertEquals(true, result[0].isSuccess);
        System.assertEquals(2, result[0].allocatedVolunteers.size());
        System.assertEquals(eventRecord.Name + ' ' + System.Label.Volunteers_Successfully_Allocated, result[0].statusMessage);
        System.assertEquals(2, assignVolunteerCount);
    }

    @IsTest
    static void testAssignVolunteersSubJuniorCategoryAllocationReturnSuccessMessageAndAllocatedVolunteerIds() {

        Event__c eventRecord = new Event__c(
            Name = 'Sub Junior Event',
            Primary_Category__c = 'Sub-Junior',
            Required_Student_Count__c = 2,
            Work_Type__c = 'Branch'
        );

        insert eventRecord;

        Test.startTest();
        List<VolunteerAllocationHandler.AssignVolunteersResponse> result = VolunteerAllocationHandler.assignVolunteers(
            new Set<Id>{ eventRecord.Id }
        );
        Test.stopTest();

        Integer assignVolunteerCount =  [SELECT COUNT()
                                            FROM Assigned_Volunteer__c
                                            WHERE Event__c = :eventRecord.Id
                                        ];

        System.assertEquals(1, result.size());
        System.assertEquals(true, result[0].isSuccess);
        System.assertEquals(2, result[0].allocatedVolunteers.size());
        System.assertEquals(2, assignVolunteerCount);
    }

    @IsTest
    static void testAssignVolunteersSeniorCategoryAllocationReturnSuccessMessageAndAllocatedVolunteerIds() {

        Event__c eventRecord = new Event__c(
            Name = 'Senior Event',
            Primary_Category__c = 'Senior',
            Required_Student_Count__c = 1,
            Work_Type__c = 'Class'
        );

        insert eventRecord;

        Test.startTest();
        List<VolunteerAllocationHandler.AssignVolunteersResponse> result = VolunteerAllocationHandler.assignVolunteers(
                new Set<Id>{ eventRecord.Id }
            );
        Test.stopTest();

        System.assertEquals(1, result.size());
        System.assertEquals(true, result[0].isSuccess);
        System.assertEquals(1, result[0].allocatedVolunteers.size());

        Student__c assignedStudent = [
            SELECT Id, Category__c
            FROM Student__c
            WHERE Id IN (
                SELECT Student__c
                FROM Assigned_Volunteer__c
                WHERE Event__c = :eventRecord.Id
            )
            LIMIT 1
        ];

        System.assertEquals('Senior', assignedStudent.Category__c);
    }
    
    @IsTest
    static void testAssignVolunteersInsufficientVolunteerReturnFailedMessage() {

        Event__c eventRecord = new Event__c(
            Name = 'Insufficient Event',
            Primary_Category__c = 'Senior',
            Required_Student_Count__c = 10,
            Work_Type__c = 'Class'
        );

        insert eventRecord;

        Test.startTest();
        List<VolunteerAllocationHandler.AssignVolunteersResponse> result = VolunteerAllocationHandler.assignVolunteers(
            new Set<Id>{ eventRecord.Id }
        );
        Test.stopTest();

        Integer assignVolunteerCount =  [SELECT COUNT()
                                            FROM Assigned_Volunteer__c
                                            WHERE Event__c = :eventRecord.Id
                                        ];

        System.assertEquals(1, result.size());
        System.assertEquals(false, result[0].isSuccess);
        System.assertEquals(0, assignVolunteerCount);
    }

    @IsTest
    static void testExistingClassWorkload() {

        Student__c seniorStudent = [SELECT Id
            FROM Student__c
            WHERE Name = 'Senior Student'
            LIMIT 1
        ];

        Event__c oldEvent = new Event__c(
            Name = 'Old Class Event',
            Primary_Category__c = 'Senior',
            Required_Student_Count__c = 1,
            Work_Type__c = 'Class'
        );

        Event__c newEvent = new Event__c(
            Name = 'New Class Event',
            Primary_Category__c = 'Senior',
            Required_Student_Count__c = 1,
            Work_Type__c = 'Class'
        );

        insert new List<Event__c>{ oldEvent, newEvent };

        insert new Assigned_Volunteer__c(
            Event__c = oldEvent.Id,
            Student__c = seniorStudent.Id,
            Assigned_Date__c = Date.today()
        );

        Test.startTest();
        List<VolunteerAllocationHandler.AssignVolunteersResponse> result = VolunteerAllocationHandler.assignVolunteers(
                new Set<Id>{ newEvent.Id }
            );
        Test.stopTest();

        System.assertEquals(1, result.size());
        System.assertEquals(true, result[0].isSuccess);
    }

    @IsTest
    static void testExistingBranchWorkload() {

        Student__c seniorStudent = [SELECT Id
            FROM Student__c
            WHERE Name = 'Senior Student'
            LIMIT 1
        ];

        Event__c oldEvent = new Event__c(
            Name = 'Old Branch Event',
            Primary_Category__c = 'Senior',
            Required_Student_Count__c = 1,
            Work_Type__c = 'Branch'
        );

        Event__c newEvent = new Event__c(
            Name = 'New Branch Event',
            Primary_Category__c = 'Senior',
            Required_Student_Count__c = 1,
            Work_Type__c = 'Branch'
        );

        insert new List<Event__c>{ oldEvent, newEvent };

        insert new Assigned_Volunteer__c(
            Event__c = oldEvent.Id,
            Student__c = seniorStudent.Id,
            Assigned_Date__c = Date.today()
        );

        Test.startTest();
        List<VolunteerAllocationHandler.AssignVolunteersResponse> result = VolunteerAllocationHandler.assignVolunteers(
                new Set<Id>{ newEvent.Id }
            );
        Test.stopTest();

        System.assertEquals(1, result.size());
        System.assertEquals(true, result[0].isSuccess);
    }

    @IsTest
    static void testExistingCollageWorkload() {

        Student__c seniorStudent = [SELECT Id
            FROM Student__c
            WHERE Name = 'Senior Student'
            LIMIT 1
        ];

        Event__c oldEvent = new Event__c(
            Name = 'Old Collage Event',
            Primary_Category__c = 'Senior',
            Required_Student_Count__c = 1,
            Work_Type__c = 'Collage'
        );

        Event__c newEvent = new Event__c(
            Name = 'New Collage Event',
            Primary_Category__c = 'Senior',
            Required_Student_Count__c = 1,
            Work_Type__c = 'Collage'
        );

        insert new List<Event__c>{ oldEvent, newEvent };
        insert new Assigned_Volunteer__c(
            Event__c = oldEvent.Id,
            Student__c = seniorStudent.Id,
            Assigned_Date__c = Date.today()
        );

        Test.startTest();
        List<VolunteerAllocationHandler.AssignVolunteersResponse> result = VolunteerAllocationHandler.assignVolunteers(
                new Set<Id>{ newEvent.Id }
            );
        Test.stopTest();

        System.assertEquals(1, result.size());
        System.assertEquals(true, result[0].isSuccess);
    }

    @IsTest
    static void testMultipleEvents() {

        Event__c event1 = new Event__c(
            Name = 'Multiple Event 1',
            Primary_Category__c = 'Junior',
            Required_Student_Count__c = 1,
            Work_Type__c = 'Class'
        );

        Event__c event2 = new Event__c(
            Name = 'Multiple Event 2',
            Primary_Category__c = 'Junior',
            Required_Student_Count__c = 1,
            Work_Type__c = 'Branch'
        );

        insert new List<Event__c>{
            event1,
            event2
        };

        Test.startTest();
        List<VolunteerAllocationHandler.AssignVolunteersResponse> result = VolunteerAllocationHandler.assignVolunteers(
            new Set<Id>{event1.Id, event2.Id}
        );
        Test.stopTest();

        Integer assignmentCount = [SELECT COUNT()
                                    FROM Assigned_Volunteer__c
                                    WHERE Event__c IN :new Set<Id>{
                                        event1.Id,
                                        event2.Id
                                    }
                                ];   

        System.assertEquals(2, result.size());
        System.assertEquals(2, assignmentCount);
    }
}