8thSept2026/volAssignment/force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/fields/Primary_Category__c.field-meta.xml
<CustomField>
    <fullName>Primary_Category__c</fullName>
    <label>Primary Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Student_Categories</valueSetName>
    </valueSet>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/fields/Required_Student_Count__c.field-meta.xml
<CustomField>
    <fullName>Required_Student_Count__c</fullName>
    <label>Required Student Count</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Occurred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/objects/Event__c/fields/Work_Type__c.field-meta.xml
<CustomField>
    <fullName>Work_Type__c</fullName>
    <label>Work Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Event_Work_Type</valueSetName>
    </valueSet>
</CustomField>

8thSept2026/volAssignment/force-app/main/default/classes/EventSelector.cls
public without sharing class EventSelector {

    public static List<Event__c> getEventsByIds(List<Id> eventIds) {

        return [
            SELECT Id,
            	   Name, //adding name so that it can be include in the binded message
                   Work_Type__c,
                   Primary_Category__c,
                   Required_Student_Count__c,
                   Status__c
            FROM Event__c
            WHERE Id IN :eventIds
        ];
    }
}